# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
name: $(Version)$(Rev:.r)
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '05f9822b-6148-4ca8-b74b-625f89323cbe'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ExampleGroup'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'template.json'
    deploymentMode: 'Incremental'
